### ISSUE TITLE
Problem when importing this lib (UNEXPECTED TOP-LEVEL EXCEPTION:)

### ISSUE THREAD

**Issue by dzfacts** [nhachicha/SnappyDB#43]
I'm trying to import the library on my project, but I'm getting that exception.

Error:Execution failed for task ':app:dexDevDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\android\sdk\build-tools\21.1.1\dx.bat --dex --no-optimize --output C:\Users\Danilo\Documents\AndroidStudioProjects\Contele GE 2.0 Mobile\app\build\intermediates\dex\dev\debug --input-list=C:\Users\Danilo\Documents\AndroidStudioProjects\Contele GE 2.0 Mobile\app\build\intermediates\tmp\dex\dev\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
		at com.android.dx.command.dexer.Main.run(Main.java:245)
		at com.android.dx.command.dexer.Main.main(Main.java:214)
		at com.android.dx.command.Main.main(Main.java:106)

I'm not Gradle expert so I could'n find a solution.

**Comment by siga111** [comment]
This line is the key:
```
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536 
```

It seems that you are over method limit and not using [multiDex](https://developer.android.com/tools/building/multidex.html).

Exception is not related to this library.
