### ISSUE TITLE
UnsatisfiedLinkError with Play Services 8.3.0

### ISSUE THREAD

**Issue by adrien-aubel** [nhachicha/SnappyDB#68]
When upgrading to Google Play Services 8.3.0 making the following changes in the Gradle file:

In buildscript.dependencies

```
classpath 'com.google.gms:google-services:1.4.0-beta3' -> classpath 'com.google.gms:google-services:1.5.0-beta2'
```

In dependencies

```
compile 'com.google.android.gms:play-services-base:8.1.0' -> compile 'com.google.android.gms:play-services-base:8.3.0'
```

The following exception gets systematically thrown:

```
11-16 12:15:22.998 3681-3681/com.invi.messenger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: ..., PID: 3681
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/...-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libsnappydb-native.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                      at java.lang.System.loadLibrary(System.java:989)
                                                                      at com.snappydb.internal.DBImpl.<clinit>(DBImpl.java:40)
                                                                      at com.snappydb.DBFactory.open(DBFactory.java:40)
                                                                      at com.snappydb.DBFactory.open(DBFactory.java:65)
                                                                      at com.snappydb.DBFactory.open(DBFactory.java:77)
```

Any idea why and if it's something that can be fixed easily?

**Comment by comparecourses** [comment]
Even we are facing the issue when upgrading play services from 8.1 to 8.3

**Comment by andreimarinescu** [comment]
same issue here. any workarounds possible?
